### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by mimmi20**
This PR (and this project) is required to solve issue browscap/browscap-php#191.

@asgrim Could you add this project on packagist

### CODE REVIEW

**Review by asgrim — CHANGES_REQUESTED** [review]
Can you rename the repo / package name please? It's not a "browscap file reader" it's an "apache logfile reader" (or parser perhaps)..let's get naming right before we push to packagist please. Otherwise :+1: from me.

**Comment by asgrim** [comment]
If the future intent is to support other server log files, maybe "http access log parser"?

**Comment by asgrim** [comment]
@mimmi20 might need re-associating in Travis/Circle/CodeCov etc.

**Comment by mimmi20** [comment]
Travis is re-assigned, Codecov adds a new project when the data are pushed, Circleci is not used here.

**Review by asgrim — APPROVED** [review]

**Pull request merged**
